language: java
jdk:
- openjdk8
sudo: false
os:
- linux
dist: xenial
cache:
  directories:
  - $HOME/.m2
before_script:
- .travis/start_cluster.sh 2
install:
- mvn clean
- mvn install
script:
- cd test
- mvn test -DskipTests=false
notifications:
  email:
  - qe-notices@aerospike.com
  - qe-notices-clients@aerospike.com
